swagger: '2.0'
info:
  version: '1.0'
  title: EPIC MAIL
  description: >
    an app for sending email to people
  contact: {}
host: 127.0.0.1:4000
basePath: /api/v1
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /auth/signup:
    post:
      description: route to sign in user
      summary: create an account
      tags:
      - users
      operationId: AuthSignupPost
      deprecated: false
      produces:
      - application/json; charset=utf-8
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: firstname
        in: formData
        required: true
        type: string
        description: ''
      - name: lastname
        in: formData
        required: true
        type: string
        description: ''
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      - name: password
        in: formData
        required: true
        type: string
        description: ''
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/createanaccount'
          examples:
            application/json; charset=utf-8:
              status: 201
              data:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiZnJhbmsiLCJsYXN0bmFtZSI6ImFuZ2VsbyIsImVtYWlsIjoiZnJhbmtAbWUuY29tIiwicGFzc3dvcmQiOiIkMmIkMDgkZUNjenlldHZ5dUZKb3M2clAxVDVhT1A3SzFhYy55SVZKVFRRRElsLm5JVlNSbERGdkdaOC4iLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRhdCI6IjIwMTktMDMtMTZUMDg6MDc6MzUuMTQ4WiIsInVwZGF0ZWRhdCI6IjIwMTktMDMtMTZUMDg6MDc6MzUuMTUwWiIsImlhdCI6MTU1MjcyNzI1NSwiZXhwIjoxNTUzMzMyMDU1fQ.9SY4jfSHjsgMNbuPRbeJAtWo3LzANQDVQdugBslqRMY
          headers:
            X-Powered-By:
              type: string
              default: Express
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Headers:
              type: string
              default: X-Requested-With
            Content-Length:
              type: string
              default: 477
            ETag:
              type: string
              default: W/"1dd-lC5Ug0145iFw2SCLjTLH1TyDnrs"
            Date:
              type: string
              default: Sat, 16 Mar 2019 09:07:35 GMT
            Connection:
              type: string
              default: keep-alive
  /auth/login:
    post:
      description: 'route to login user '
      summary: login user
      tags:
      - users
      operationId: AuthLoginPost
      deprecated: false
      produces:
      - application/json; charset=utf-8
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      - name: password
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/loginuser'
          examples:
            application/json; charset=utf-8:
              status: 200
              data:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiZnJhbmsiLCJsYXN0bmFtZSI6ImFuZ2VsbyIsImVtYWlsIjoiZnJhbmtAbWUuY29tIiwicGFzc3dvcmQiOiIkMmIkMDgkZUNjenlldHZ5dUZKb3M2clAxVDVhT1A3SzFhYy55SVZKVFRRRElsLm5JVlNSbERGdkdaOC4iLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRhdCI6IjIwMTktMDMtMTZUMDg6MDc6MzUuMTQ4WiIsInVwZGF0ZWRhdCI6IjIwMTktMDMtMTZUMDg6MDc6MzUuMTUwWiIsImlhdCI6MTU1MjcyNzU1MCwiZXhwIjoxNTUzMzMyMzUwfQ.OMdPnUf3sDIlUY849kTb3Fx8liKyPkrfitolHgZgwh8
          headers:
            X-Powered-By:
              type: string
              default: Express
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Headers:
              type: string
              default: X-Requested-With
            Content-Length:
              type: string
              default: 477
            ETag:
              type: string
              default: W/"1dd-XtYujnMMO4Wq7bl3okT4ZMb7I5M"
            Date:
              type: string
              default: Sat, 16 Mar 2019 09:12:30 GMT
            Connection:
              type: string
              default: keep-alive
  /messages:
    post:
      description: create and send email to another user
      summary: create and send message
      tags:
      - messages
      operationId: MessagesPost
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: subject
        in: formData
        required: true
        type: string
        description: ''
      - name: message
        in: formData
        required: true
        type: string
        description: ''
      - name: status
        in: formData
        required: true
        type: string
        description: ''
      - name: recieversEmail
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
    get:
      description: get all users messages as inbox messages
      summary: get inbox messages
      tags:
      - messages
      operationId: MessagesGet
      deprecated: false
      produces:
      - application/json; charset=utf-8
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/getinboxmessages'
          headers:
            X-Powered-By:
              type: string
              default: Express
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Headers:
              type: string
              default: X-Requested-With
            Content-Length:
              type: string
              default: 465
            ETag:
              type: string
              default: W/"1d1-n3K3IJx0AQ/+U70EdMnV/tG51NQ"
            Date:
              type: string
              default: Sat, 16 Mar 2019 10:12:29 GMT
            Connection:
              type: string
              default: keep-alive
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/tokenunavailable'
          examples:
            application/json:
              status: 401
              error:
              - Token is not provided
  /messages/sent:
    get:
      description: 'get all users sent messages '
      summary: get sent messages
      tags:
      - messages
      operationId: MessagesSentGet
      deprecated: false
      produces:
      - application/json; charset=utf-8
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/getsentmessages'
          headers:
            X-Powered-By:
              type: string
              default: Express
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Headers:
              type: string
              default: X-Requested-With
            Content-Length:
              type: string
              default: 429
            ETag:
              type: string
              default: W/"1ad-SuuPfXfIYwFIekasYDTMd4gNsaM"
            Date:
              type: string
              default: Sat, 16 Mar 2019 10:28:33 GMT
            Connection:
              type: string
              default: keep-alive
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/tokenunavailable'
          examples:
            application/json:
              status: 401
              error:
              - Token is not provided
  /messages/unread:
    get:
      description: 'gets all users unread messages '
      summary: get users unread messages
      tags:
      - messages
      operationId: MessagesUnreadGet
      deprecated: false
      produces:
      - application/json; charset=utf-8
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/getusersunreadmessages'
          examples:
            application/json; charset=utf-8:
              status: 200
              data:
              - id: 3
                subject: 'congrates '
                message: ' dear, frank heard about you joining andela. more greatness man. God bless'
                parentmessageid: 
                status: sent
                receiverid: 1
                senderid: 2
                read: true
                createdon: 2019-03-16T08:27:08.9810000Z
          headers:
            X-Powered-By:
              type: string
              default: Express
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Headers:
              type: string
              default: X-Requested-With
            Content-Length:
              type: string
              default: 260
            ETag:
              type: string
              default: W/"104-QM1w21kOM/62JAqvkRUUub799RI"
            Date:
              type: string
              default: Sat, 16 Mar 2019 11:02:24 GMT
            Connection:
              type: string
              default: keep-alive
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/tokenunavailable'
          examples:
            application/json:
              status: 401
              error:
              - Token is not provided
  /messages/3:
    get:
      description: get a particular users email from the inbox
      summary: get a particular  email message
      tags:
      - messages
      operationId: Messages3Get
      deprecated: false
      produces:
      - application/json; charset=utf-8
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/getaparticularInboxmessage'
          examples:
            application/json; charset=utf-8:
              status: 200
              data:
              - id: 3
                subject: 'congrates '
                message: ' dear, frank heard about you joining andela. more greatness man. God bless'
                parentmessageid: 
                status: sent
                receiverid: 1
                senderid: 2
                read: true
                createdon: 2019-03-16T08:27:08.9810000Z
          headers:
            X-Powered-By:
              type: string
              default: Express
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Headers:
              type: string
              default: X-Requested-With
            Content-Length:
              type: string
              default: 260
            ETag:
              type: string
              default: W/"104-QM1w21kOM/62JAqvkRUUub799RI"
            Date:
              type: string
              default: Sat, 16 Mar 2019 11:27:45 GMT
            Connection:
              type: string
              default: keep-alive
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/tokenunavailable'
          examples:
            application/json:
              status: 401
              error:
              - Token is not provided
    delete:
      description: 'user can delete message '
      summary: delete  message
      tags:
      - messages
      operationId: Messages3Delete
      deprecated: false
      produces:
      - application/json; charset=utf-8
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        202:
          description: ''
          schema:
            $ref: '#/definitions/deletemessage'
          examples:
            application/json; charset=utf-8:
              status: 202
              data:
              - message: deleted successfully
          headers:
            X-Powered-By:
              type: string
              default: Express
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Headers:
              type: string
              default: X-Requested-With
            Content-Length:
              type: string
              default: 58
            ETag:
              type: string
              default: W/"3a-YU6BJFz6mKfslKs4PP/+b8msSdg"
            Date:
              type: string
              default: Sat, 16 Mar 2019 13:12:30 GMT
            Connection:
              type: string
              default: keep-alive
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/tokenunavailable'
          examples:
            application/json:
              status: 401
              error:
              - Token is not provided
definitions:
  createanaccount:
    title: createanaccount
    example:
      status: 201
      data:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiZnJhbmsiLCJsYXN0bmFtZSI6ImFuZ2VsbyIsImVtYWlsIjoiZnJhbmtAbWUuY29tIiwicGFzc3dvcmQiOiIkMmIkMDgkZUNjenlldHZ5dUZKb3M2clAxVDVhT1A3SzFhYy55SVZKVFRRRElsLm5JVlNSbERGdkdaOC4iLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRhdCI6IjIwMTktMDMtMTZUMDg6MDc6MzUuMTQ4WiIsInVwZGF0ZWRhdCI6IjIwMTktMDMtMTZUMDg6MDc6MzUuMTUwWiIsImlhdCI6MTU1MjcyNzI1NSwiZXhwIjoxNTUzMzMyMDU1fQ.9SY4jfSHjsgMNbuPRbeJAtWo3LzANQDVQdugBslqRMY
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data'
    required:
    - status
    - data
  Data:
    title: Data
    type: object
    properties:
      token:
        type: string
    required:
    - token
  loginuser:
    title: loginuser
    example:
      status: 200
      data:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiZnJhbmsiLCJsYXN0bmFtZSI6ImFuZ2VsbyIsImVtYWlsIjoiZnJhbmtAbWUuY29tIiwicGFzc3dvcmQiOiIkMmIkMDgkZUNjenlldHZ5dUZKb3M2clAxVDVhT1A3SzFhYy55SVZKVFRRRElsLm5JVlNSbERGdkdaOC4iLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRhdCI6IjIwMTktMDMtMTZUMDg6MDc6MzUuMTQ4WiIsInVwZGF0ZWRhdCI6IjIwMTktMDMtMTZUMDg6MDc6MzUuMTUwWiIsImlhdCI6MTU1MjcyNzU1MCwiZXhwIjoxNTUzMzMyMzUwfQ.OMdPnUf3sDIlUY849kTb3Fx8liKyPkrfitolHgZgwh8
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data'
    required:
    - status
    - data
  getinboxmessages:
    title: getinboxmessages
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data3'
    required:
    - status
    - data
  Data3:
    title: Data3
    type: object
    properties:
      id:
        example: 3
        type: integer
        format: int32
      subject:
        example: 'congrates '
        type: string
      message:
        example: ' dear, frank heard about you joining andela. more greatness man. God bless'
        type: string
      parentmessageid:
        type: string
      status:
        example: sent
        type: string
      receiverid:
        example: 1
        type: integer
        format: int32
      senderid:
        example: 2
        type: integer
        format: int32
      read:
        example: false
        type: boolean
      createdon:
        example: 3/16/2019 8:27:08 AM
        type: string
    required:
    - id
    - subject
    - message
    - status
    - receiverid
    - senderid
    - read
    - createdon
  getsentmessages:
    title: getsentmessages
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data3'
    required:
    - status
    - data
  tokenunavailable:
    title: tokenunavailable
    example:
      status: 401
      error:
      - Token is not provided
    type: object
    properties:
      status:
        type: integer
        format: int32
      error:
        type: array
        items:
          type: string
    required:
    - status
    - error
  getusersunreadmessages:
    title: getusersunreadmessages
    example:
      status: 200
      data:
      - id: 3
        subject: 'congrates '
        message: ' dear, frank heard about you joining andela. more greatness man. God bless'
        parentmessageid: 
        status: sent
        receiverid: 1
        senderid: 2
        read: true
        createdon: 2019-03-16T08:27:08.9810000Z
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data3'
    required:
    - status
    - data
  getaparticularInboxmessage:
    title: getaparticularInboxmessage
    example:
      status: 200
      data:
      - id: 3
        subject: 'congrates '
        message: ' dear, frank heard about you joining andela. more greatness man. God bless'
        parentmessageid: 
        status: sent
        receiverid: 1
        senderid: 2
        read: true
        createdon: 2019-03-16T08:27:08.9810000Z
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data3'
    required:
    - status
    - data
  deletemessage:
    title: deletemessage
    example:
      status: 202
      data:
      - message: deleted successfully
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data7'
    required:
    - status
    - data
  Data7:
    title: Data7
    type: object
    properties:
      message:
        example: deleted successfully
        type: string
    required:
    - message
tags:
- name: users
  description: user routes which includes sign in and sign out
- name: messages
  description: route that contains messages endpoints